import React, { useState, useMemo } from 'react';
import { useAuthStore } from '../store/useAuthStore';
import { supabase } from '../lib/supabase';
import { Priority, Category } from '../types';
import { ChevronLeft, Coins, AlertCircle } from 'lucide-react';

interface CreateTaskScreenProps {
  onNavigate: (screen: 'dashboard') => void;
}

const priorities: Priority[] = ['low', 'medium', 'high'];
const categories: { id: Category; label: string; icon: string }[] = [
  { id: 'work', label: 'Work', icon: '💼' },
  { id: 'personal', label: 'Personal', icon: '👤' },
  { id: 'health', label: 'Health', icon: '❤️' },
  { id: 'learning', label: 'Learning', icon: '📚' },
  { id: 'sport', label: 'Sport', icon: '⚽' },
  { id: 'rest', label: 'Rest', icon: '🛌' },
];

export const CreateTaskScreen: React.FC<CreateTaskScreenProps> = ({ onNavigate }) => {
  const { user } = useAuthStore();
  const [title, setTitle] = useState('');
  const [description, setDescription] = useState('');
  const [priority, setPriority] = useState<Priority>('medium');
  const [category, setCategory] = useState<Category>('personal');
  const [isSubmitting, setIsSubmitting] = useState(false);

  // Client-side reward estimation (mimics DB logic)
  const estimatedReward = useMemo(() => {
    let base = 10;
    if (priority === 'low') base = 5;
    if (priority === 'high') base = 15;

    let multiplier = 1.0;
    if (category === 'sport') multiplier = 1.2;
    if (category === 'health') multiplier = 1.3;
    if (category === 'learning') multiplier = 1.5;

    return Math.round(base * multiplier);
  }, [priority, category]);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!title.trim() || !user) return;

    setIsSubmitting(true);
    try {
      const { error } = await supabase.from('tasks').insert({
        user_id: user.user_id,
        title: title.trim(),
        description: description.trim() || null,
        priority,
        category,
        is_active: true
        // coin_value is generated by DB
      });

      if (error) throw error;

      // Success
      onNavigate('dashboard');
    } catch (error) {
      console.error('Error creating task:', error);
      alert('Could not create task. Please try again.');
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <div className="min-h-screen bg-white">
      {/* Header */}
      <div className="sticky top-0 bg-white z-10 px-4 py-4 border-b border-gray-100 flex items-center">
        <button 
          onClick={() => onNavigate('dashboard')}
          className="p-2 -ml-2 text-gray-600 hover:bg-gray-50 rounded-full"
        >
          <ChevronLeft size={24} />
        </button>
        <h1 className="text-lg font-bold text-gray-900 ml-2">New Habit</h1>
      </div>

      <form onSubmit={handleSubmit} className="p-5 pb-10 space-y-6">
        
        {/* Title Input */}
        <div className="space-y-2">
          <label className="text-sm font-semibold text-gray-700">What needs to be done?</label>
          <input
            type="text"
            value={title}
            onChange={(e) => setTitle(e.target.value)}
            placeholder="e.g. Read 10 pages"
            className="w-full p-4 bg-gray-50 border border-gray-200 rounded-xl focus:outline-none focus:ring-2 focus:ring-primary/50 focus:border-primary transition-all text-lg"
            required
            maxLength={100}
            autoFocus
          />
        </div>

        {/* Categories Grid */}
        <div className="space-y-3">
          <label className="text-sm font-semibold text-gray-700">Category</label>
          <div className="grid grid-cols-3 gap-3">
            {categories.map((cat) => (
              <button
                key={cat.id}
                type="button"
                onClick={() => setCategory(cat.id)}
                className={`flex flex-col items-center justify-center p-3 rounded-xl border transition-all ${
                  category === cat.id
                    ? 'bg-primary/10 border-primary text-primary'
                    : 'bg-white border-gray-200 text-gray-500 hover:bg-gray-50'
                }`}
              >
                <span className="text-2xl mb-1">{cat.icon}</span>
                <span className="text-xs font-medium">{cat.label}</span>
              </button>
            ))}
          </div>
        </div>

        {/* Priority Selection */}
        <div className="space-y-3">
          <label className="text-sm font-semibold text-gray-700">Priority & Difficulty</label>
          <div className="flex p-1 bg-gray-100 rounded-xl">
            {priorities.map((p) => (
              <button
                key={p}
                type="button"
                onClick={() => setPriority(p)}
                className={`flex-1 py-2 text-sm font-medium rounded-lg capitalize transition-all ${
                  priority === p
                    ? 'bg-white text-gray-900 shadow-sm'
                    : 'text-gray-500 hover:text-gray-700'
                }`}
              >
                {p}
              </button>
            ))}
          </div>
        </div>

        {/* Description (Optional) */}
        <div className="space-y-2">
          <label className="text-sm font-semibold text-gray-700">Notes (Optional)</label>
          <textarea
            value={description}
            onChange={(e) => setDescription(e.target.value)}
            placeholder="Add any details..."
            rows={3}
            className="w-full p-3 bg-gray-50 border border-gray-200 rounded-xl focus:outline-none focus:ring-2 focus:ring-primary/50 text-sm"
          />
        </div>

        {/* Reward Preview */}
        <div className="bg-amber-50 p-4 rounded-xl border border-amber-100 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="bg-amber-100 p-2 rounded-lg text-amber-600">
              <Coins size={20} />
            </div>
            <div>
              <p className="text-sm font-bold text-amber-800">Reward</p>
              <p className="text-xs text-amber-600">Earned upon completion</p>
            </div>
          </div>
          <span className="text-xl font-black text-amber-600">+{estimatedReward}</span>
        </div>

        {/* Submit Button */}
        <div className="pt-4">
          <button
            type="submit"
            disabled={isSubmitting || !title.trim()}
            className="w-full bg-primary text-white py-4 rounded-2xl font-bold text-lg shadow-lg shadow-primary/30 active:scale-95 transition-all disabled:opacity-50 disabled:shadow-none"
          >
            {isSubmitting ? 'Creating...' : 'Create Task'}
          </button>
        </div>

      </form>
    </div>
  );
};
