export type Priority = 'low' | 'medium' | 'high';
export type Category = 'sport' | 'health' | 'work' | 'learning' | 'rest' | 'personal';
export type TaskStatus = 'pending' | 'completed';

export interface User {
  user_id: string;
  telegram_id: number;
  username?: string;
  full_name?: string;
  avatar_url?: string;
  level: number;
  total_coins: number;
  current_streak: number;
  longest_streak: number;
  experience_points: number;
}

// Maps to 'tasks' table in Supabase
// Note: We map 'is_active' (db) to 'status' (ui) for cleaner frontend logic
export interface Task {
  id: string; // maps to task_id
  user_id: string;
  title: string;
  description?: string;
  priority: Priority;
  category: Category;
  status: TaskStatus; // derived from is_active
  coins_reward: number; // maps to coin_value
  created_at: string;
  due_time?: string;
}

export interface CreateTaskDTO {
  title: string;
  description?: string;
  priority: Priority;
  category: Category;
  user_id: string;
  // coin_value is generated by DB, but we calculate display value in UI
}
